---
apiVersion: v1
kind: Pod
metadata:
  name: quadlet-nginx
spec:
  containers:
  - name: nginx
    image: docker.io/library/nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
